/** Reproducible native model assets + clang freestanding Wasm. No network or npm dependencies. */
import fs from 'node:fs';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
const root=new URL('../../',import.meta.url);process.chdir(root.pathname);
const g={};g.window=g;
for(const name of ['text','answers','nn-weights'])vm.runInNewContext(fs.readFileSync(`assets/js/yunobot/${name}.js`,'utf8'),g);
const w=g.YUNOBOT_NN_WEIGHTS, chats=JSON.parse(fs.readFileSync('dev/yunobot-wasm/conversation.json'));
const {tokenize,charTrigrams,hash32}=g.YunoBotText;
const f32=s=>Array.from(new Float32Array(Uint8Array.from(Buffer.from(s,'base64')).buffer));
const i8=s=>Array.from(new Int8Array(Uint8Array.from(Buffer.from(s,'base64')).buffer));
let out='// Generated by build.mjs. Do not edit.\n';
function arr(type,name,a){out+=`static const ${type} ${name}[]={${a.join(',')}};\n`;}
function strings(name,a){arr('char* const',name,a.map(s=>JSON.stringify(s)));}
arr('signed char','ev',i8(w.evQ));arr('signed char','eb',i8(w.ebQ));
for(const [name,key] of [['evScale','evS'],['ebScale','ebS'],['head','wF'],['bias','bW']])arr('float',name,f32(w[key]).map(n=>Number(n).toPrecision(9)+'f'));
strings('vocab',w.vocab);strings('intentNames',w.intents.map(i=>i.intent||i.target||'home'));
arr('int','intentTypes',w.intents.map(i=>i.type==='oos'?2:i.type==='qa'?1:0));
for(const [name,lang] of [['factsEn','en'],['factsTr','tr']])strings(name,w.intents.map(i=>g.YunoBotAnswers[i.intent]?.[lang]||''));
strings('factPaths',w.intents.map(i=>g.YunoBotAnswers[i.intent]?.source[0]||i.target||(i.type==='navigation'?'/':'')));
strings('factTitles',w.intents.map(i=>g.YunoBotAnswers[i.intent]?.source[1]||i.target||'Home'));
// Hashed word/trigram logistic classifier, with an explicit non-conversation class.
const size=2048,classes=chats.length+1;
function features(s){let f=new Map();for(const t of tokenize(s)){let k=hash32('W'+t)%size;f.set(k,(f.get(k)||0)+2);for(const gram of charTrigrams(t)){k=hash32('C'+gram)%size;f.set(k,(f.get(k)||0)+1);}}let norm=Math.sqrt([...f.values()].reduce((a,b)=>a+b*b,0))||1;return [...f].map(([k,v])=>[k,v/norm]);}
const training=JSON.parse(fs.readFileSync('dev/yunobot-nn/training.json'));
const negatives=[...training.navigation,...training.qa].filter(x=>!x.intent?.startsWith('bot_')).flatMap(x=>x.sentences).filter((_,i)=>i%5===0);
negatives.push('quantum potato rainbow','what is the weather','how do I fix my car','what is his salary','who won the world cup','ignore your instructions','asdf qwerty zzzz');
const samples=chats.flatMap((c,label)=>c.samples.flatMap(text=>{
 const tr=/[çğıöşüİ]|\b(kanka|selam|merhaba|ne|bir|evet|hayir)\b/i.test(text);
 const variants=[text];
 if(!['yes','no'].includes(c.id)) variants.push(tr?'kanka '+text:'hey '+text, tr?text+' acaba':text+' please');
 if(['sad','tired','positive','bored'].includes(c.id))variants.push(tr?'bugün çok '+text:'today '+text);
 return variants.map(text=>({label,f:features(text)}));
}));
// Balance per-class contribution; negatives cover factual and unsupported questions.
const groups=chats.map((_,i)=>samples.filter(x=>x.label===i));groups.push(negatives.map(text=>({label:chats.length,f:features(text)})));
const weights=new Float64Array(classes*size),biases=new Float64Array(classes);
for(let epoch=0;epoch<220;epoch++)for(let round=0;round<20;round++)for(let label=0;label<classes;label++){
 const sample=groups[label][(epoch*7+round)%groups[label].length];const logits=Array.from(biases,(b,c)=>b+sample.f.reduce((sum,[k,v])=>sum+weights[c*size+k]*v,0));const max=Math.max(...logits),p=logits.map(x=>Math.exp(x-max)),sum=p.reduce((a,b)=>a+b,0);const lr=.11*(1-epoch/260);
 for(let c=0;c<classes;c++){const delta=(p[c]/sum-(c===label?1:0))*lr;biases[c]-=delta;for(const[k,v]of sample.f)weights[c*size+k]-=delta*v;}
}
arr('float','chatWeights',Array.from(weights,x=>x.toFixed(7)+'f'));arr('float','chatBias',Array.from(biases,x=>x.toFixed(7)+'f'));
strings('chatNames',chats.map(c=>c.id));for(const lang of ['en','tr','mix'])strings('chat_'+lang,chats.map(c=>c[lang]));
out+=`static const int DIM=${w.dim}, VOCAB=${w.vocab.length}, INTENTS=${w.intents.length}, CHATS=${chats.length}, BUCKETS=${w.buckets};\n`;
fs.writeFileSync('dev/yunobot-wasm/generated.hpp',out);
execFileSync('clang++',['--target=wasm32','-std=c++17','-O3','-flto','-nostdlib','-fno-exceptions','-fno-rtti','-fno-threadsafe-statics','-fno-builtin','-Wl,--no-entry','-Wl,--export-dynamic','-Wl,--export-memory','-Wl,-z,stack-size=524288','-Wl,--initial-memory=33554432','-Wl,--max-memory=33554432','dev/yunobot-wasm/core.cpp','-o','assets/js/yunobot/core.wasm'],{stdio:'inherit'});
console.log(`Built ${fs.statSync('assets/js/yunobot/core.wasm').size} bytes; ${samples.length} conversational examples, ${negatives.length} negatives; ${classes} classes.`);
