<?php
putenv('MODE=development');putenv('DB_CONNECTION=sqlite');putenv('DB_NAME=:memory:');
$_SERVER['HTTP_HOST']='localhost';$_SERVER['PHP_SELF']='/index.php';
require __DIR__.'/../../models/YunoBotKnowledge.php';
$db = Database::getInstance()->getConnection();
$db->exec('CREATE TABLE blog_posts (title TEXT, slug TEXT, content TEXT, updated_at TEXT, created_at TEXT, status TEXT)');
$stmt=$db->prepare('INSERT INTO blog_posts VALUES (?, ?, ?, ?, ?, ?)');
$stmt->execute(['Public article','public','<p>A public paragraph containing useful project details and Unicode: Öğrenme.</p><script>alert(1)</script>','2026-09-08','2026-09-08','published']);
$stmt->execute(['Secret draft','draft','Private unpublished material is never part of the public source index.','2026-09-08','2026-09-08','draft']);
$snapshot=(new YunoBotKnowledge($db))->snapshot();
if(count($snapshot['publishedUrls'])!==1||count($snapshot['passages'])!==1)throw new RuntimeException('Public-only selection failed');
if(str_contains(json_encode($snapshot),'Secret')||str_contains(json_encode($snapshot),'alert'))throw new RuntimeException('Unsafe/private content exposed');
if(!str_contains($snapshot['passages'][0]['text'],'Öğrenme'))throw new RuntimeException('Unicode lost');
$db->exec("UPDATE blog_posts SET status='draft'");
if((new YunoBotKnowledge($db))->snapshot()['publishedUrls']!==[])throw new RuntimeException('Unpublished article retained');
echo "4 public source snapshot checks passed\n";
$db->exec('CREATE TABLE updates (id INTEGER, title TEXT, description TEXT, update_date TEXT, mastodon_last_error TEXT)');
$db->exec("INSERT INTO updates VALUES (1,'Public update','A published update about a real project.','2026-09-09','PRIVATE TOKEN')");
$db->exec('CREATE TABLE portfolio_projects (id INTEGER, title TEXT, description TEXT, technologies TEXT)');
$db->exec("INSERT INTO portfolio_projects VALUES (1,'Test project','Public description','PHP, C++')");
$db->exec('CREATE TABLE travel_locations (id INTEGER, city TEXT, country TEXT, visited TEXT)');
$db->exec("INSERT INTO travel_locations VALUES (1,'Test city','Test country','2026-01-01')");
$db->exec('CREATE TABLE gallery_images (id INTEGER, title TEXT, is_archived INTEGER, filename TEXT)');
$db->exec("INSERT INTO gallery_images VALUES (1,'Public image',0,'private-filename.jpg'),(2,'Archived secret',1,'hidden.jpg')");
$all=(new YunoBotKnowledge($db))->snapshot();
if(count($all['passages'])!==4||count($all['scopes'])!==5)throw new RuntimeException('Public collections missing');
$json=json_encode($all);
foreach(['PRIVATE TOKEN','private-filename','Archived secret','hidden.jpg'] as $private)if(str_contains($json,$private))throw new RuntimeException('Private field leaked');
$db->exec('UPDATE gallery_images SET is_archived=1');
$all=(new YunoBotKnowledge($db))->snapshot();
if(in_array(FULL_BASE_PATH.'gallery',$all['publishedUrls'],true))throw new RuntimeException('Archived gallery retained');
echo "3 collection privacy and removal checks passed\n";
