/** Offline, deterministic corpus build. Refresh public sources with refresh.py first. */
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root = new URL('../../', import.meta.url);
const corpus = JSON.parse(readFileSync(new URL('dev/yunobot-kb/corpus.json', root), 'utf8'));
if (corpus.version !== 2 || corpus.passages.length < 20) throw new Error('Invalid source corpus');
const output = '/** Public source passages; generated by dev/yunobot-kb/build.mjs. */\nwindow.YUNOBOT_KB = ' + JSON.stringify(corpus) + ';\n';
const target = new URL('assets/js/yunobot/knowledge-pack.js', root);
writeFileSync(target, output);
console.log(`Built ${corpus.passages.length} passages (${Math.round(output.length/1024)} KiB), ${corpus.digest}`);
