<?php
/**
 * Open-source project catalog for /downloads.
 *
 * Facts (description, language, licence, requirements, release) are taken from
 * each GitHub repository's README/metadata. `cover` is a file in
 * assets/images/downloads/: real in-app screenshots or repository artwork.
 * `release` is only set where the repo publishes a release with a file.
 */
return [
    [
        'slug' => 'onehour',
        'title' => 'One Hour',
        'kind' => 'Game · RTS',
        'repo' => 'yunusemrejr/onehour',
        'cover' => 'onehour.webp',
        'cover_alt' => 'One Hour in play: a Cyber Army Command Core and Fabricator on a fogged map with the build panel below.',
        'description' => 'A compact skirmish real-time strategy game in the spirit of Command & Conquer: Generals – Zero Hour. One map, two armies (Cyber and Clanker), you against one to three AI opponents. No campaign, no multiplayer.',
        'language' => 'C++',
        'license' => null,
        'platforms' => ['Linux'],
        'requires' => ['g++ and make', 'SDL2 runtime (libsdl2-2.0-0); SDL2 headers are vendored'],
        'run' => './run.sh',
        'release' => null,
    ],
    [
        'slug' => 'minispaceshooter',
        'title' => 'Mini Space Shooter',
        'kind' => 'Game · arcade',
        'repo' => 'yunusemrejr/minispaceshooter',
        'cover' => 'minispaceshooter.webp',
        'cover_alt' => 'Mini Space Shooter title screen: pixel-art logo, menu with Start Run, Leaderboard, Medal Wall, Controls and Quit.',
        'description' => 'A pixel-art space shooter written in C11 and C++17 with endless levels. Fixed-capacity pools and its own online learners adapt enemy movement and tactics to how you fly, with hard limits on raw difficulty.',
        'language' => 'C / C++',
        'license' => 'MIT',
        'platforms' => ['Linux (Wayland and X11)'],
        'requires' => ['build-essential, libx11-dev, libxext-dev', 'Optional: SDL2 runtime for native Wayland'],
        'run' => './run.sh',
        'release' => null,
    ],
    [
        'slug' => 'self-improving-rat',
        'title' => 'Self Improving Rat',
        'kind' => 'Artificial life · ML',
        'repo' => 'yunusemrejr/self-improving-rat',
        'cover' => 'self-improving-rat.webp',
        'cover_alt' => 'Self Improving Rat: the rat and a cheese wedge in a maze, with the learning panel and a worked probability formula underneath.',
        'description' => 'A persistent artificial-life rat in a procedurally generated maze: a recurrent reinforcement-learning agent with homeostasis, curiosity and episodic memory that saves its whole state between runs. No GPU, no ML framework, no network.',
        'language' => 'C++20',
        'license' => null,
        'platforms' => ['Linux (tested on Ubuntu 26.04)'],
        'requires' => ['cmake 3.16+, g++ and make or ninja', 'libsdl2-dev (the test suite needs no SDL)'],
        'run' => './run.sh',
        'release' => null,
    ],
    [
        'slug' => 'pocketharness',
        'title' => 'PocketHarness',
        'kind' => 'Developer tool · coding agent',
        'repo' => 'yunusemrejr/pocketharness',
        'cover' => 'pocketharness.webp',
        'cover_alt' => 'The PocketHarness mascot, a pocket-sized toolbox robot, above the loop terminal, agent loop, model, tool, Linux, result.',
        'description' => 'A deliberately tiny, Linux-native coding-agent harness in a single C++ binary: a chat TUI, slash commands and autonomous goals, with no SDKs, plugins or MCP layer. Linux does the general-purpose work.',
        'language' => 'C++20',
        'license' => 'MIT',
        'platforms' => ['Linux x86_64'],
        'requires' => ['g++ (C++20), make and curl', 'Optional: Chrome, FFmpeg, llama.cpp for screenshots, video and the local judge'],
        'run' => null,
        'release' => ['tag' => 'v0.13.2', 'label' => 'Linux x86_64 tarball', 'url' => 'https://github.com/yunusemrejr/pocketharness/releases/tag/v0.13.2'],
    ],
    [
        'slug' => 'yunuspi',
        'title' => 'YunusPi',
        'kind' => 'Developer tool · coding agent',
        'repo' => 'yunusemrejr/yunuspi',
        'cover' => 'yunuspi.webp',
        'cover_alt' => 'YunusPi project intelligence viewer: a dependency graph around a Checkout component with filters and evidence panels.',
        'description' => 'An independently maintained coding agent harness with its own core (historically derived from Pi 0.85.1): persistent project memory, bounded subagents, an advisory layer and safety hooks. You bring the model provider.',
        'language' => 'JavaScript',
        'license' => 'MIT',
        'platforms' => ['Linux', 'Windows via WSL2 Ubuntu', 'macOS via an Ubuntu VM'],
        'requires' => ['Node.js 22.19+ and npm', 'git, curl, bash, ripgrep, python3, build-essential, bubblewrap'],
        'run' => null,
        'release' => ['tag' => 'v0.18.0', 'label' => 'Release notes', 'url' => 'https://github.com/yunusemrejr/yunuspi/releases/tag/v0.18.0'],
    ],
    [
        'slug' => 'finny',
        'title' => 'Finny',
        'kind' => 'Desktop app · finance',
        'repo' => 'yunusemrejr/finny',
        'cover' => 'finny.webp',
        'cover_alt' => 'Finny desktop window: a chat comparing the policy rate in the US and China with a small bar chart and source line.',
        'description' => 'A local-first personal finance assistant with a native desktop window. It answers rates, inflation, FX and calculator questions with a Naive-Bayes classifier and fuzzy matching, not a language model, and cites public sources.',
        'language' => 'Rust',
        'license' => null,
        'platforms' => ['Linux (Ubuntu)'],
        'requires' => ['Rust stable toolchain (run.sh can install it via rustup)', 'X11 or Wayland client libraries'],
        'run' => './run.sh',
        'release' => null,
    ],
    [
        'slug' => 'dataclean',
        'title' => 'Dataclean',
        'kind' => 'Desktop app · disk cleanup',
        'repo' => 'yunusemrejr/dataclean',
        'cover' => 'dataclean.webp',
        'cover_alt' => 'Dataclean Duplicates view: groups of identical files such as holiday.mp4 and panorama.jpg, each listing its copies with one marked as staying.',
        'description' => 'A small GTK 4 app that shows where your disk space goes and finds byte-identical duplicates and forgotten leftovers. Nothing is deleted: files go to the Trash after a confirmation, with checks right before each move and an undo.',
        'language' => 'C',
        'license' => 'MIT',
        'platforms' => ['Linux (GTK 4)'],
        'requires' => ['gcc and make tools (build-essential)', 'GTK 4 runtime; run.sh fetches the dev headers locally if missing'],
        'run' => './run.sh',
        'release' => null,
    ],
];
